// <auto-generated />
using System;
using ExcaliburCodingAssignment.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExcaliburCodingAssignment.Migrations
{
    [DbContext(typeof(ExcaliburDbContext))]
    [Migration("20200425202612_addedseedcode")]
    partial class addedseedcode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExcaliburCodingAssignment.Models.OrderCombined", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("OrderAmount")
                        .HasColumnType("float");

                    b.Property<string>("OrderDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCombined");
                });

            modelBuilder.Entity("ExcaliburCodingAssignment.Models.OrderDate", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.ToTable("OrderDate");

                    b.HasData(
                        new
                        {
                            OrderID = 20,
                            OrderedDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 21,
                            OrderedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 22,
                            OrderedDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 23,
                            OrderedDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ExcaliburCodingAssignment.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("OrderAmount")
                        .HasColumnType("float");

                    b.Property<string>("OrderDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            OrderAmount = 2000.0,
                            OrderDesc = "Order 2000",
                            OrderId = 20
                        },
                        new
                        {
                            Id = 21,
                            OrderAmount = 2100.0,
                            OrderDesc = "Order 2100",
                            OrderId = 21
                        },
                        new
                        {
                            Id = 22,
                            OrderAmount = 2200.0,
                            OrderDesc = "Order 2200",
                            OrderId = 22
                        },
                        new
                        {
                            Id = 23,
                            OrderAmount = 2300.0,
                            OrderDesc = "Order 2300",
                            OrderId = 23
                        });
                });

            modelBuilder.Entity("ExcaliburCodingAssignment.Models.OrderCombined", b =>
                {
                    b.HasOne("ExcaliburCodingAssignment.Models.OrderDate", "OrderDate")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExcaliburCodingAssignment.Models.OrderDetail", b =>
                {
                    b.HasOne("ExcaliburCodingAssignment.Models.OrderDate", "OrderDate")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
